package com.civicflow.resource.enums;

public enum ResourceAdminOperation {
    CREATE_OUTLET,
    UPDATE_OUTLET,
    CHANGE_OUTLET_STATUS,
    DELETE_OUTLET,
    CREATE_ITEM,
    UPDATE_ITEM,
    CHANGE_ITEM_STATUS,
    DELETE_ITEM,
    CREATE_WINDOW,
    UPDATE_WINDOW,
    CHANGE_WINDOW_STATUS,
    DELETE_WINDOW,
    REPLACE_WINDOW_ITEMS,
    CREATE_SLOT,
    BATCH_CREATE_SLOTS,
    UPDATE_SLOT,
    CHANGE_SLOT_STATUS,
    ADJUST_SLOT_QUOTA
}
