CREATE TABLE appointment_reservation_request (
    id BIGINT UNSIGNED NOT NULL,
    reservation_id CHAR(36) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    idempotency_key_hash BINARY(32) NOT NULL,
    payload_hash BINARY(32) NOT NULL,
    slot_id BIGINT UNSIGNED NOT NULL,
    outlet_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    service_date DATE NOT NULL,
    slot_start_time TIME(0) NOT NULL,
    slot_end_time TIME(0) NOT NULL,
    outlet_name_snapshot VARCHAR(128) NOT NULL,
    item_name_snapshot VARCHAR(128) NOT NULL,
    total_quota INT UNSIGNED NOT NULL,
    release_at DATETIME(3) NOT NULL,
    close_at DATETIME(3) NOT NULL,
    slot_status VARCHAR(32) NOT NULL,
    slot_config_version BIGINT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL,
    failure_code VARCHAR(64) NULL,
    event_json LONGTEXT NULL,
    trace_id VARCHAR(64) NOT NULL,
    reserved_at DATETIME(3) NULL,
    reservation_expires_at DATETIME(3) NULL,
    publish_attempts INT UNSIGNED NOT NULL DEFAULT 0,
    last_error_code VARCHAR(64) NULL,
    next_recovery_at DATETIME(3) NOT NULL,
    recovery_owner VARCHAR(64) NULL,
    recovery_lease_until DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_reservation_request_id (reservation_id),
    UNIQUE KEY uk_reservation_request_idempotency (user_id, idempotency_key_hash),
    KEY idx_reservation_request_recovery (status, next_recovery_at, recovery_lease_until, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
